server:
  port: 8081

spring:
  application:
    name: market-ingest-streamer
  config:
    import: classpath:upbit-markets.yml

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

upbit:
  websocket:
    uri: wss://api.upbit.com/websocket/v1
    environment: development
    data-types:
      ticker:
        enabled: true
      trade:
        enabled: true
      orderbook:
        enabled: true

rabbitmq:
  exchange:
    market-data: market-data.exchange

logging:
  level:
    com.rabbittick.streamer: debug